# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FullStackSocial_ios_lbta' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FullStackSocial_ios_lbta

end
